#+TITLE: Ruby on Windows Guides - The Book
#+SUBTITLE: 2012-03-07
#+DATE: <2012-03-07 Wed>
#+TAGS: ruby rails book

I use Windows on my everyday work. First thing I do after installing
Windows is to set up complete environment for Ruby. In “ancient” days
(measuring in computer years, of course) I have used One Click
Installer. Later, [[http://www.rubyinstaller.org][RubyInstaller]] came on the scene.

With much better foundations, RubyInstaller simplified Ruby usage and
made it look like on Linux, Ruby’s native platform. Key benefit of
RubyInstaller over One Click installer was possibility to install Ruby
native gems written in C. Switching from commercial VisualStudio, used
in One Click Installer, to MinGW build tool-chain in RubyInstaller was
crucial decision made by Luis Lavena, great author of RubyInstaller.

After RubyInstaller, one more project appeared with the goal to
simplify Ruby on Rails installation and usage on
Windows. RailsInstaller. I haven’t tried it, but I’m sure it will help
increasing number of Rails users on Windows.

But do you really need installer for Ruby on Rails on Windows? It
depends of your attitude. If you are not interested what is going on
behind the scenes and just want to be able to start using Rails after
few mouse clicks RailsInstaller is definitely for you.

If, on the other hand, you want to know how things work, you should
try to install Ruby on Rails without installer. With RubyInstaller
installing Ruby on Rails on Windows is, actually, just a matter of
issuing

#+BEGIN_SRC sh
gem install rails
gem install sqlite3
#+END_SRC

Of course you might face problems building and installing some gems,
primarily because gem authors don’t want to bother with Windows
support or simply because gems rely of third party libraries that are
not ported to Windows. In any case you can ask for help on
[[http://groups.google.com/group/rubyinstaller][RubyInstaller mailing list]].

People wonder if Ruby and Ruby on Rails are really usable on
Windows. My opinion is that they are. Of course, there are some
problems mainly with speed, but I would dare to say that solutions are
on the way and hopefully very soon this will not be problem any
more. I guess main reason why they are not so widespread on Windows
platforms is scepticism and lack of experience.

As one of contributors to RubyInstaller project I noticed same
questions are repeated on RubyInstaller mailing list. Mainly because
of lack of familiarity with Ruby and RoR on Windows. That’s why I
decided to write [[http://rubyonwindowsguides.github.com][a book]] where I tried to give deeper insight on all
details about installing and using Ruby and Ruby on Rails on
Windows. The [[http://rubyonwindowsguides.github.io][Ruby on Windows Guides]] is still in beta. However it
already covers the most important issues and I think all novices and
advanced developers can learn something new from it. Work on the book
is still in progress so if you have any suggestions, ideas and wishes
you can send them as an [[https://github.com/rubyonwindowsguides/rubyonwindowsguides.github.com/issues][issue on the GitHub]].

If you want to get deeper understanding of Ruby and Ruby on Rails on
Windows, find out how to build native gems in several ways or just
want to get an idea for what you can use Ruby on Windows go ahead and
read the book. Of course I expect your comments, here or on GitHub.
