# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pragmatic Development Notes
subtitle: Software development stuff
author: Boško Ivanišević
email: bosko.ivanisevic@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pragdevnotes.com"
keywords: ["Programming", "Physics", "Ruby", "JavaScript", "Elixir", "RaspberryPI"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Belgrade
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-feed
  - jekyll-gist

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Boško Ivanišević
  avatar: #pdn-logo.png
  job: "Developer"
  bio: "Ruby, JavaScript, C++ and few more others developer."
  email: bosko.ivanisevic@gmail.com
  disqus-shortname: #
  twitter: boskoivanisevic #username
  facebook: #username
  google:
    plus: BoškoIvanišević
    analytics: UA-4023697-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: bosko #username
  stackoverflow: 1665470/boško-ivanišević  # from a "http://stackoverflow.com/users/123456/username" link
  linkedin: boskoivanisevic #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
