#+TITLE: Still on CVS? Too Bad!
#+SUBTITLE: 2009-06-05
#+DATE: <2009-06-05 Fri>
#+TAGS: emacs git

At the and of May 2009 Savannah disks crashed. You can read more about
it [[http://lists.gnu.org/archive/html/savannah-users/2009-05/msg00023.html][here]]. This is something no one can predict. You never know when
your hardware will let you down, and there is no cure for that. Disks
will be replaced, system reinstalled, backups restored and that’s
it. Or is it?

Not completely if you are using CVS or SVN and there were some commits
after the last backup. Emacs developers spent few days in the
[[http://lists.gnu.org/archive/html/emacs-devel/2009-06/msg00056.html][discussion]] to determine what commits they lost.

Luckily they had Git mirror of CVS repository but what surprises me is
they didn’t move to Git yet. If they were using Git they would have
been able to restore complete repository in a few minutes (maybe
longer for large repositories). Since they already have Git mirror for
Emacs code I really do not understand why do they not switch to Git
completely. Having full history at each developer’s computer is a huge
benefit. Not to mention that Git gives you possibilities you can only
dream of in CVS and SVN.
